sonar.projectKey=imaginario27
sonar.organization=imaginario27

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=tests/coverage/lcov.info

sonar.qualitygate.wait=false

sonar.exclusions=**/node_modules/**,**/.nuxt/**,**/dist/**,**/.output/**,**/coverage/**
