sonar.projectKey=imaginario27_imaginario27-portfolio_6e485fe9-dff3-4a8b-85d8-444661076ebd
sonar.host.url=https://sonarqube.imaginario27.com

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=tests/coverage/lcov.info

sonar.qualitygate.wait=false

sonar.exclusions=**/node_modules/**,**/.nuxt/**,**/dist/**,**/.output/**,**/coverage/**