query Menu($language: String!, $location: MenuLocationEnum!) {
    menuItems(where: { location: $location, language: $language }) {
        nodes {
            id
            label
            uri
            parentId
        }
    }
}
