<template>
    <div
        :class="[
            'relative',
            'w-full',
            'h-[calc(100vh-72px)]',
            'overflow-hidden',
        ]"
    >
        <InfiniteLandscape
            width="100%"
            height="100%"
            :cameraZ="125"
            :planeSize="256"
            :speed="0.5"
        />
        <div
            :class="[
                'absolute',
                'inset-0',
                'z-2',
                'flex',
                'flex-col',
                'items-center',
                'justify-start',
                'text-center',
                'px-6',
                'pt-[18vh]',
            ]"
        >
            <h1
                :class="[
                    'm-0',
                    'font-bold',
                    'tracking-[-0.03em]',
                    'text-text-default',
                    'text-[clamp(2.5rem,8vw,6rem)]',
                ]"
            >
                Imaginario27
            </h1>
            <p
                :class="[
                    'mt-3',
                    'max-w-xl',
                    'text-text-neutral-subtle',
                    'text-[clamp(1rem,1.5vw,1.25rem)]',
                ]"
            >
                Diseño &amp; desarrollo de experiencias digitales
            </p>
            <div
                :class="[
                    'mt-8',
                    'flex',
                    'flex-wrap',
                    'items-center',
                    'justify-center',
                    'gap-3',
                    'pointer-events-auto',
                ]"
            >
                <ActionButton
                    :size="ButtonSize.XXL"
                    :styleType="ButtonStyleType.PRIMARY_BRAND_FILLED"
                    text="Ver proyectos"
                />
                <ActionButton
                    :size="ButtonSize.XXL"
                    :styleType="ButtonStyleType.NEUTRAL_OUTLINED"
                    text="Contáctame"
                />
            </div>
        </div>
    </div>
</template>